db_ip: 104.45.26.208
db_port: 3306

backends:
  - name: backend1
    backend_ip: 23.101.76.200
    backend_port: 8080

frontend_ip: 23.97.186.142
frontend_port: 8080

frontend_backend_ip: 23.101.76.200
frontend_backend_port: 8080