#! /bin/bash
MASTER_ADDRESS=$1
MASTER_PORT=$2

sudo mysql -e "
CHANGE REPLICATION SOURCE TO
SOURCE_HOST='$MASTER_ADDRESS',
SOURCE_PORT = $MASTER_PORT,
SOURCE_USER='repl',
SOURCE_PASSWORD='slavepassword',
GET_MASTER_PUBLIC_KEY=1;"